//! Adapter rendering: generate tool entrypoints from engine templates.
//!
//! Templates use {{placeholder}} tokens resolved from config.
//! Literal single braces (e.g. `{slug}`) are NOT expanded (AC-07).

use std::collections::BTreeMap;
use std::fmt;
use std::path::Path;

use crate::config::{Config, checked_repo_path, validate_repo_relative_path};
use crate::manifest::engine_version_label;

pub(crate) const MARKER_PREFIX: &str = "generated by mochiflow";
pub(crate) const MANAGED_BLOCK_END: &str = "<!-- mochiflow:end -->";

/// Resolve a user-facing adapter label to its canonical adapter ID.
///
/// `codex` is a recognizable tool name shown in the init menu / accepted on
/// `--adapter`, but its on-disk artifact (`AGENTS.md`) is produced by the
/// neutral `agents` adapter. All other labels map to themselves. Resolution is
/// applied only at the input boundary (CLI / prompt); `generate` and `doctor`
/// read the stored config verbatim so an unknown ID surfaces as schema-invalid
/// and a doctor FAIL.
pub fn resolve_adapter_label(label: &str) -> &str {
    match label {
        "codex" => "agents",
        other => other,
    }
}

/// Resolve a list of input labels to canonical IDs, preserving order and
/// removing duplicates (e.g. `["codex", "agents"]` -> `["agents"]`).
pub fn resolve_adapter_labels(labels: &[String]) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for label in labels {
        let id = resolve_adapter_label(label).to_string();
        if !out.contains(&id) {
            out.push(id);
        }
    }
    out
}

/// Build the substitution map from config (matching Python's _subs).
fn subs(cfg: &Config, tool: &str) -> BTreeMap<String, String> {
    let engine = format!("{}/engine", cfg.install_dir);
    let engine_version = engine_version_label(&cfg.engine_dir());
    let mut m = BTreeMap::new();
    m.insert(
        "marker".into(),
        format!("{MARKER_PREFIX} adapter={tool} version={engine_version}"),
    );
    m.insert("engine".into(), engine);
    m.insert("install_dir".into(), cfg.install_dir.clone());
    m.insert("specs_dir".into(), cfg.specs_dir.clone());
    m.insert("specs_glob".into(), format!("{}/**", cfg.specs_dir));
    m.insert(
        "artifact_language".into(),
        cfg.i18n.artifact_language.clone(),
    );
    m.insert(
        "conversation_language".into(),
        cfg.i18n.conversation_language.clone(),
    );
    m.insert("engine_version".into(), engine_version);
    m.insert("adapter_tool".into(), tool.to_string());
    m.insert(
        "constitution.project".into(),
        cfg.constitution.project.clone(),
    );
    m.insert("constitution.local".into(), cfg.constitution.local.clone());
    m.insert("context.product".into(), cfg.context.product.clone());
    m.insert("context.structure".into(), cfg.context.structure.clone());
    m.insert("context.tech".into(), cfg.context.tech.clone());
    m.insert("adr.decisions".into(), cfg.adr.decisions.clone());
    m.insert("adr.pitfalls".into(), cfg.adr.pitfalls.clone());
    m.insert("index".into(), cfg.index.clone());
    m.insert("base_branch".into(), cfg.git.base_branch.clone());
    m.insert("pr_command".into(), cfg.git.pr_command.clone());
    m
}

/// Literal {{key}} replacement — does NOT touch single braces (AC-07).
pub fn render(template: &str, substitutions: &BTreeMap<String, String>) -> String {
    let mut result = template.to_string();
    for (key, value) in substitutions {
        let token = format!("{{{{{key}}}}}"); // produces "{{key}}"
        result = result.replace(&token, value);
    }
    result
}

fn is_kiro_agent_json(out_rel: &str) -> bool {
    matches!(
        out_rel,
        ".kiro/agents/spec-plan-auditor.json" | ".kiro/agents/spec-change-reviewer.json"
    )
}

/// Whether a generated Kiro agent JSON tolerates a user-pinned `model`.
///
/// The read-only reviewer agents are model-customizable: a user may pin a
/// different review model, so a model-only diff is not drift and the pinned
/// model is preserved on regenerate.
fn kiro_agent_preserves_model(out_rel: &str) -> bool {
    is_kiro_agent_json(out_rel)
}

/// Kiro steering `.md` files are full-file managed targets, not block-embeddable
/// ones: a Kiro steering file needs its `inclusion:` frontmatter at the very top
/// of the file, so a markerless pre-existing file must be overwritten whole
/// rather than have a managed block appended mid-file.
fn is_kiro_full_file_md(out_rel: &str) -> bool {
    out_rel.starts_with(".kiro/steering/") && out_rel.ends_with(".md")
}

/// Deprecated mochiflow-managed Kiro outputs from earlier adapter versions.
/// Self-heal removes only the entries here that still carry `MARKER_PREFIX`;
/// files not on this list are never scanned, removed, or reported. This single
/// static list drives both the write branch (remove markered, record preserved)
/// and the check branch (report lingering markered residue as drift) so the two
/// can never disagree.
const DEPRECATED_KIRO_PATHS: &[&str] = &[
    ".kiro/agents/spec-builder.json",
    ".kiro/agents/spec-worker.json",
    ".kiro/agents/spec-independent-reviewer.json",
    ".kiro/steering/spec.md",
    ".kiro/steering/spec-discuss.md",
    ".kiro/steering/spec-plan.md",
    ".kiro/steering/spec-build.md",
    ".kiro/steering/spec-ship.md",
    ".kiro/steering/spec-patch.md",
    ".kiro/steering/spec-review.md",
    ".kiro/steering/spec-refresh-context.md",
    ".kiro/hooks/generate-project-index.kiro.hook",
];

/// Scan the static deprecated-path list for the `kiro` adapter.
///
/// Write mode: remove each listed path that carries the marker (recording it in
/// `removed`) and record a listed-but-markerless path in `preserved` without
/// deleting it. Check mode: report a lingering markered path as drift so
/// `adapter generate --check` / `doctor` catch un-regenerated projects. Paths
/// that are absent, and any path not on the list, are left entirely alone.
fn self_heal_deprecated_kiro(cfg: &Config, check: bool, result: &mut AdapterResult) {
    for rel in DEPRECATED_KIRO_PATHS {
        let path = cfg.repo_root.join(rel);
        let content = match std::fs::read_to_string(&path) {
            Ok(c) => c,
            Err(_) => continue,
        };
        let markered = content.contains(MARKER_PREFIX);
        if check {
            if markered {
                result.drift.push((*rel).to_string());
            }
            continue;
        }
        if markered {
            match std::fs::remove_file(&path) {
                Ok(()) => result.removed.push((*rel).to_string()),
                Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
                Err(e) => result
                    .errors
                    .push(format!("could not remove deprecated {rel}: {e}")),
            }
        } else {
            result.preserved.push((*rel).to_string());
        }
    }
}

fn parse_json_object(content: &str) -> Option<serde_json::Map<String, serde_json::Value>> {
    match serde_json::from_str::<serde_json::Value>(content).ok()? {
        serde_json::Value::Object(obj) => Some(obj),
        _ => None,
    }
}

fn kiro_agent_matches_rendered(out_rel: &str, current: &str, rendered: &str) -> bool {
    if current == rendered {
        return true;
    }
    if !kiro_agent_preserves_model(out_rel) || !current.contains(MARKER_PREFIX) {
        return false;
    }

    let mut current_obj = match parse_json_object(current) {
        Some(obj) => obj,
        None => return false,
    };
    let mut rendered_obj = match parse_json_object(rendered) {
        Some(obj) => obj,
        None => return false,
    };
    current_obj.remove("model");
    rendered_obj.remove("model");
    current_obj == rendered_obj
}

pub(crate) fn is_embeddable_target(out_rel: &str) -> bool {
    out_rel.ends_with(".md")
}

pub(crate) fn managed_block_begin(tool: &str) -> String {
    format!("<!-- mochiflow:begin adapter={tool} -->")
}

fn managed_block(tool: &str, rendered: &str) -> String {
    let mut block = String::new();
    block.push_str(&managed_block_begin(tool));
    block.push('\n');
    block.push_str(rendered);
    if !block.ends_with('\n') {
        block.push('\n');
    }
    block.push_str(MANAGED_BLOCK_END);
    block.push('\n');
    block
}

pub(crate) fn managed_block_bounds(content: &str, tool: &str) -> Option<(usize, usize)> {
    let begin = managed_block_begin(tool);
    let start = content.find(&begin)?;
    let after_start = start + begin.len();
    let end_rel = content[after_start..].find(MANAGED_BLOCK_END)?;
    let mut end = after_start + end_rel + MANAGED_BLOCK_END.len();
    if content[end..].starts_with("\r\n") {
        end += 2;
    } else if content[end..].starts_with('\n') {
        end += 1;
    }
    Some((start, end))
}

fn replace_managed_block(content: &str, tool: &str, block: &str) -> Option<String> {
    let (start, end) = managed_block_bounds(content, tool)?;
    let mut out = String::new();
    out.push_str(&content[..start]);
    out.push_str(block);
    out.push_str(&content[end..]);
    Some(out)
}

fn append_managed_block(content: &str, block: &str) -> String {
    if content.is_empty() {
        return block.to_string();
    }

    let mut out = content.to_string();
    if !out.ends_with('\n') {
        out.push('\n');
    }
    if !out.ends_with("\n\n") {
        out.push('\n');
    }
    out.push_str(block);
    out
}

fn embeddable_target_matches_rendered(
    out_rel: &str,
    tool: &str,
    current: &str,
    rendered: &str,
) -> bool {
    if current == rendered {
        return true;
    }
    if !is_embeddable_target(out_rel) {
        return false;
    }
    let Some((start, end)) = managed_block_bounds(current, tool) else {
        return false;
    };
    current[start..end] == managed_block(tool, rendered)
}

fn preserve_kiro_agent_model(out_rel: &str, current: Option<&str>, rendered: &str) -> String {
    if !kiro_agent_preserves_model(out_rel) {
        return rendered.to_string();
    }

    let Some(current) = current else {
        return rendered.to_string();
    };
    if !current.contains(MARKER_PREFIX) {
        return rendered.to_string();
    }

    let Some(current_obj) = parse_json_object(current) else {
        return rendered.to_string();
    };
    let Some(model) = current_obj.get("model").cloned() else {
        return rendered.to_string();
    };
    let Some(mut rendered_obj) = parse_json_object(rendered) else {
        return rendered.to_string();
    };
    rendered_obj.insert("model".into(), model);
    match serde_json::to_string_pretty(&serde_json::Value::Object(rendered_obj)) {
        Ok(json) => format!("{json}\n"),
        Err(_) => rendered.to_string(),
    }
}

/// Load adapter manifest.toml → (adapter_dir, ordered file mappings).
///
/// File order matches the manifest's TOML declaration order (Python parity for
/// the `wrote:` / `DRIFT:` output); `toml`'s `preserve_order` feature keeps the
/// parsed table in insertion order.
#[derive(Debug)]
pub(crate) enum AdapterManifestError {
    MissingManifest {
        tool: String,
        path: std::path::PathBuf,
    },
    Read {
        tool: String,
        path: std::path::PathBuf,
        source: std::io::Error,
    },
    InvalidToml {
        tool: String,
        path: std::path::PathBuf,
        source: Box<toml::de::Error>,
    },
    MissingFiles {
        tool: String,
        path: std::path::PathBuf,
    },
    InvalidFileMapping {
        tool: String,
        path: std::path::PathBuf,
        target: String,
    },
    UnsafeMapping {
        tool: String,
        mapping: String,
        message: String,
    },
}

impl fmt::Display for AdapterManifestError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MissingManifest { tool, path } => {
                write!(f, "adapter {tool} manifest missing: {}", path.display())
            }
            Self::Read { tool, path, source } => {
                write!(
                    f,
                    "adapter {tool} manifest read failed at {}: {source}",
                    path.display()
                )
            }
            Self::InvalidToml { tool, path, source } => {
                write!(
                    f,
                    "adapter {tool} manifest invalid TOML at {}: {source}",
                    path.display()
                )
            }
            Self::MissingFiles { tool, path } => {
                write!(
                    f,
                    "adapter {tool} manifest missing [files] table: {}",
                    path.display()
                )
            }
            Self::InvalidFileMapping { tool, path, target } => {
                write!(
                    f,
                    "adapter {tool} manifest maps {target} to a non-string template path: {}",
                    path.display()
                )
            }
            Self::UnsafeMapping {
                tool,
                mapping,
                message,
            } => write!(f, "adapter {tool} unsafe mapping {mapping}: {message}"),
        }
    }
}

pub(crate) fn load_manifest(
    cfg: &Config,
    tool: &str,
) -> Result<(std::path::PathBuf, Vec<(String, String)>), AdapterManifestError> {
    let adir = cfg.engine_dir().join("adapters").join(tool);
    let manifest_path = adir.join("manifest.toml");
    if !manifest_path.exists() {
        return Err(AdapterManifestError::MissingManifest {
            tool: tool.to_string(),
            path: manifest_path,
        });
    }
    let text =
        std::fs::read_to_string(&manifest_path).map_err(|source| AdapterManifestError::Read {
            tool: tool.to_string(),
            path: manifest_path.clone(),
            source,
        })?;
    let data: toml::Value = text
        .parse()
        .map_err(|source| AdapterManifestError::InvalidToml {
            tool: tool.to_string(),
            path: manifest_path.clone(),
            source: Box::new(source),
        })?;
    let files = data
        .get("files")
        .and_then(toml::Value::as_table)
        .ok_or_else(|| AdapterManifestError::MissingFiles {
            tool: tool.to_string(),
            path: manifest_path.clone(),
        })?;
    let mut map = Vec::new();
    for (k, v) in files {
        let Some(tpl) = v.as_str() else {
            return Err(AdapterManifestError::InvalidFileMapping {
                tool: tool.to_string(),
                path: manifest_path.clone(),
                target: k.clone(),
            });
        };
        validate_repo_relative_path("adapter output", k).map_err(|error| {
            AdapterManifestError::UnsafeMapping {
                tool: tool.to_string(),
                mapping: k.clone(),
                message: error.to_string(),
            }
        })?;
        validate_repo_relative_path("adapter template", tpl).map_err(|error| {
            AdapterManifestError::UnsafeMapping {
                tool: tool.to_string(),
                mapping: tpl.to_string(),
                message: error.to_string(),
            }
        })?;
        checked_repo_path(&adir, "adapter template", tpl).map_err(|error| {
            AdapterManifestError::UnsafeMapping {
                tool: tool.to_string(),
                mapping: tpl.to_string(),
                message: error.to_string(),
            }
        })?;
        cfg.checked_path("adapter output", k).map_err(|error| {
            AdapterManifestError::UnsafeMapping {
                tool: tool.to_string(),
                mapping: k.clone(),
                message: error.to_string(),
            }
        })?;
        map.push((k.clone(), tpl.to_string()));
    }
    Ok((adir, map))
}

pub struct AdapterResult {
    pub drift: Vec<String>,
    pub wrote: Vec<String>,
    pub blocked: Vec<BlockedAdapter>,
    pub errors: Vec<String>,
    /// Deprecated marker-bearing Kiro outputs removed by self-heal (write mode).
    pub removed: Vec<String>,
    /// Deprecated-list Kiro outputs kept because they lack the marker (write mode).
    pub preserved: Vec<String>,
}

pub struct BlockedAdapter {
    pub target: String,
    pub candidate: String,
}

/// Generate adapter files (or check for drift).
pub fn generate(cfg: &Config, check: bool, force: bool) -> AdapterResult {
    let mut result = AdapterResult {
        drift: Vec::new(),
        wrote: Vec::new(),
        blocked: Vec::new(),
        errors: Vec::new(),
        removed: Vec::new(),
        preserved: Vec::new(),
    };

    for tool in &cfg.adapter_tools() {
        let (adir, files) = match load_manifest(cfg, tool) {
            Ok(v) => v,
            Err(e) => {
                result.errors.push(e.to_string());
                continue;
            }
        };
        let substitutions = subs(cfg, tool);

        for (out_rel, tpl_rel) in &files {
            let tpl_path = adir.join(tpl_rel);
            let template = match std::fs::read_to_string(&tpl_path) {
                Ok(t) => t,
                Err(e) => {
                    result.errors.push(format!(
                        "adapter {tool} template missing or unreadable for {out_rel} at {}: {e}",
                        tpl_path.display()
                    ));
                    continue;
                }
            };
            let rendered = render(&template, &substitutions);
            let target = match cfg.checked_path("adapter output", out_rel) {
                Ok(path) => path.into_operation_path(),
                Err(error) => {
                    result.errors.push(error.to_string());
                    continue;
                }
            };
            let current = std::fs::read_to_string(&target).ok();

            if check {
                let matches = current.as_deref().is_some_and(|cur| {
                    if is_kiro_full_file_md(out_rel) {
                        cur == rendered
                    } else {
                        embeddable_target_matches_rendered(out_rel, tool, cur, &rendered)
                            || kiro_agent_matches_rendered(out_rel, cur, &rendered)
                    }
                });
                if !matches {
                    result.drift.push(out_rel.clone());
                }
                continue;
            }

            if let Some(ref cur) = current
                && !force
            {
                if is_kiro_full_file_md(out_rel) {
                    // Full-file managed: fall through to the whole-file write
                    // below so `inclusion: always` frontmatter stays at the top,
                    // overwriting a markerless pre-existing file rather than
                    // appending a managed block mid-file.
                } else if is_embeddable_target(out_rel) {
                    let block = managed_block(tool, &rendered);
                    let rendered = if managed_block_bounds(cur, tool).is_some() {
                        replace_managed_block(cur, tool, &block).unwrap_or_else(|| cur.clone())
                    } else if cur.contains(MARKER_PREFIX) {
                        rendered.clone()
                    } else {
                        append_managed_block(cur, &block)
                    };
                    if let Some(parent) = target.parent()
                        && let Err(e) = std::fs::create_dir_all(parent)
                    {
                        let parent_label = Path::new(out_rel)
                            .parent()
                            .map(|p| p.display().to_string())
                            .unwrap_or_else(|| ".".to_string());
                        result.errors.push(format!(
                            "could not create target parent for {out_rel} at {parent_label}: {e}"
                        ));
                        continue;
                    }
                    if let Err(e) = std::fs::write(&target, &rendered) {
                        result.errors.push(format!(
                            "could not write target for {out_rel} at {out_rel}: {e}"
                        ));
                        continue;
                    }
                    result.wrote.push(out_rel.clone());
                    continue;
                }

                if is_kiro_full_file_md(out_rel) || cur.contains(MARKER_PREFIX) {
                    // Full-file managed (Kiro steering) and managed non-embeddable
                    // targets fall through to the whole-file update below.
                } else {
                    let candidate = format!("{}/state/adapters/{out_rel}", cfg.install_dir);
                    let candidate_path = match cfg.checked_path("adapter candidate", &candidate) {
                        Ok(path) => path.into_operation_path(),
                        Err(error) => {
                            result.errors.push(error.to_string());
                            continue;
                        }
                    };
                    if let Some(parent) = candidate_path.parent()
                        && let Err(e) = std::fs::create_dir_all(parent)
                    {
                        let parent_label = Path::new(&candidate)
                            .parent()
                            .map(|p| p.display().to_string())
                            .unwrap_or_else(|| candidate.clone());
                        result.errors.push(format!(
                            "could not create candidate parent for {out_rel} at {parent_label}: {e}"
                        ));
                        continue;
                    }
                    if let Err(e) = std::fs::write(&candidate_path, &rendered) {
                        result.errors.push(format!(
                            "could not write candidate for {out_rel} at {candidate}: {e}"
                        ));
                        continue;
                    }
                    result.blocked.push(BlockedAdapter {
                        target: out_rel.clone(),
                        candidate,
                    });
                    continue;
                }
            }

            let rendered = preserve_kiro_agent_model(out_rel, current.as_deref(), &rendered);
            if let Some(parent) = target.parent()
                && let Err(e) = std::fs::create_dir_all(parent)
            {
                let parent_label = Path::new(out_rel)
                    .parent()
                    .map(|p| p.display().to_string())
                    .unwrap_or_else(|| ".".to_string());
                result.errors.push(format!(
                    "could not create target parent for {out_rel} at {parent_label}: {e}"
                ));
                continue;
            }
            if let Err(e) = std::fs::write(&target, &rendered) {
                result.errors.push(format!(
                    "could not write target for {out_rel} at {out_rel}: {e}"
                ));
                continue;
            }
            result.wrote.push(out_rel.clone());
        }

        if tool == "kiro" {
            self_heal_deprecated_kiro(cfg, check, &mut result);
        }
    }

    result
}

/// CLI entry point for `adapter generate`.
pub fn cmd_adapter_generate(cfg: &Config, check: bool, force: bool) -> i32 {
    let result = generate(cfg, check, force);
    if check {
        for f in &result.drift {
            println!("DRIFT: {f}");
        }
        for error in &result.errors {
            println!("FAIL: {error}");
        }
        println!(
            "\nSummary: {} drift, {} failed",
            result.drift.len(),
            result.errors.len()
        );
        if result.drift.is_empty() && result.errors.is_empty() {
            0
        } else {
            1
        }
    } else {
        for f in &result.wrote {
            println!("wrote: {f}");
        }
        for f in &result.removed {
            println!("removed: {f}");
        }
        for f in &result.preserved {
            println!("preserved: {f}");
        }
        for blocked in &result.blocked {
            println!(
                "BLOCKED: {} (candidate: {}; merge manually or use --force to replace)",
                blocked.target, blocked.candidate
            );
        }
        for error in &result.errors {
            println!("FAIL: {error}");
        }
        println!(
            "\nSummary: {} written, {} blocked, {} failed",
            result.wrote.len(),
            result.blocked.len(),
            result.errors.len()
        );
        if result.blocked.is_empty() && result.errors.is_empty() {
            0
        } else {
            1
        }
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    #[test]
    fn subs_exposes_layer_tokens() {
        use crate::config::{
            Config, I18nConfig, I18nMeta, I18nValueSource, RawAdapter, RawAdr, RawConstitution,
            RawContext, RawGit,
        };
        let cfg = Config {
            schema_version: 1,
            i18n: I18nConfig {
                artifact_language: "en".into(),
                conversation_language: "auto".into(),
            },
            i18n_meta: I18nMeta {
                has_i18n_table: true,
                has_legacy_language: false,
                missing_artifact_language: false,
                missing_conversation_language: false,
                artifact_source: I18nValueSource::I18n,
                conversation_source: I18nValueSource::I18n,
            },
            install_dir: ".mochiflow".into(),
            specs_dir: ".mochiflow/specs".into(),
            index: ".mochiflow/INDEX.md".into(),
            constitution: RawConstitution {
                project: ".mochiflow/constitution.md".into(),
                local: ".mochiflow/constitution.local.md".into(),
            },
            context: RawContext {
                product: ".mochiflow/context/product.md".into(),
                structure: ".mochiflow/context/structure.md".into(),
                tech: ".mochiflow/context/tech.md".into(),
            },
            adr: RawAdr {
                decisions: ".mochiflow/adr/decisions".into(),
                pitfalls: ".mochiflow/adr/pitfalls".into(),
            },
            git: RawGit::default(),
            adapter: RawAdapter::default(),
            surfaces: BTreeMap::new(),
            repo_root: std::path::PathBuf::from("/tmp"),
            config_path: std::path::PathBuf::from("/tmp/.mochiflow/config.toml"),
        };
        let m = subs(&cfg, "kiro");
        assert_eq!(
            m.get("context.product").map(String::as_str),
            Some(".mochiflow/context/product.md")
        );
        assert_eq!(
            m.get("context.structure").map(String::as_str),
            Some(".mochiflow/context/structure.md")
        );
        assert_eq!(
            m.get("context.tech").map(String::as_str),
            Some(".mochiflow/context/tech.md")
        );
        assert_eq!(
            m.get("adr.decisions").map(String::as_str),
            Some(".mochiflow/adr/decisions")
        );
        assert_eq!(
            m.get("adr.pitfalls").map(String::as_str),
            Some(".mochiflow/adr/pitfalls")
        );
        assert_eq!(
            m.get("constitution.project").map(String::as_str),
            Some(".mochiflow/constitution.md")
        );
        assert_eq!(
            m.get("constitution.local").map(String::as_str),
            Some(".mochiflow/constitution.local.md")
        );
        // legacy flat tokens are gone
        assert!(!m.contains_key("paths.architecture"));
        assert!(!m.contains_key("paths.structure"));
        assert_eq!(
            m.get("specs_glob").map(String::as_str),
            Some(".mochiflow/specs/**")
        );
    }

    #[test]
    fn resolve_label_codex_to_agents() {
        assert_eq!(resolve_adapter_label("codex"), "agents");
    }

    #[test]
    fn resolve_label_identity_for_others() {
        assert_eq!(resolve_adapter_label("agents"), "agents");
        assert_eq!(resolve_adapter_label("kiro"), "kiro");
        assert_eq!(resolve_adapter_label("claude-code"), "claude-code");
        assert_eq!(resolve_adapter_label("copilot"), "copilot");
        // unknown labels pass through unchanged (doctor/schema reject them)
        assert_eq!(resolve_adapter_label("foo"), "foo");
    }

    #[test]
    fn resolve_labels_dedupes_preserving_order() {
        let input = vec![
            "codex".to_string(),
            "agents".to_string(),
            "kiro".to_string(),
        ];
        assert_eq!(resolve_adapter_labels(&input), vec!["agents", "kiro"]);
    }

    #[test]
    fn render_replaces_double_brace_tokens() {
        let mut subs = BTreeMap::new();
        subs.insert("engine".to_string(), ".mochiflow/engine".to_string());
        subs.insert("artifact_language".to_string(), "ja".to_string());
        subs.insert("conversation_language".to_string(), "auto".to_string());
        let out = render(
            "engine={{engine}} artifact={{artifact_language}} conversation={{conversation_language}}",
            &subs,
        );
        assert_eq!(
            out,
            "engine=.mochiflow/engine artifact=ja conversation=auto"
        );
    }

    #[test]
    fn render_leaves_single_brace_literal_untouched() {
        // AC-07: literal single-brace tokens like {slug} must NOT be expanded.
        let mut subs = BTreeMap::new();
        subs.insert("slug".to_string(), "SHOULD-NOT-APPEAR".to_string());
        let out = render("path/{slug}/spec.yaml and {{slug}}", &subs);
        assert_eq!(out, "path/{slug}/spec.yaml and SHOULD-NOT-APPEAR");
    }

    #[test]
    fn render_repeats_and_missing_keys() {
        let mut subs = BTreeMap::new();
        subs.insert("k".to_string(), "V".to_string());
        // repeated token replaced everywhere; unknown {{x}} left as-is
        assert_eq!(render("{{k}}-{{k}}-{{x}}", &subs), "V-V-{{x}}");
    }

    fn config_with_root(root: std::path::PathBuf) -> crate::config::Config {
        use crate::config::{
            Config, I18nConfig, I18nMeta, I18nValueSource, RawAdapter, RawAdr, RawConstitution,
            RawContext, RawGit,
        };
        let config_path = root.join(".mochiflow/config.toml");
        Config {
            schema_version: 1,
            i18n: I18nConfig {
                artifact_language: "en".into(),
                conversation_language: "auto".into(),
            },
            i18n_meta: I18nMeta {
                has_i18n_table: true,
                has_legacy_language: false,
                missing_artifact_language: false,
                missing_conversation_language: false,
                artifact_source: I18nValueSource::I18n,
                conversation_source: I18nValueSource::I18n,
            },
            install_dir: ".mochiflow".into(),
            specs_dir: ".mochiflow/specs".into(),
            index: ".mochiflow/INDEX.md".into(),
            constitution: RawConstitution {
                project: ".mochiflow/constitution.md".into(),
                local: ".mochiflow/constitution.local.md".into(),
            },
            context: RawContext {
                product: ".mochiflow/context/product.md".into(),
                structure: ".mochiflow/context/structure.md".into(),
                tech: ".mochiflow/context/tech.md".into(),
            },
            adr: RawAdr {
                decisions: ".mochiflow/adr/decisions".into(),
                pitfalls: ".mochiflow/adr/pitfalls".into(),
            },
            git: RawGit::default(),
            adapter: RawAdapter::default(),
            surfaces: BTreeMap::new(),
            repo_root: root,
            config_path,
        }
    }

    fn empty_result() -> AdapterResult {
        AdapterResult {
            drift: Vec::new(),
            wrote: Vec::new(),
            blocked: Vec::new(),
            errors: Vec::new(),
            removed: Vec::new(),
            preserved: Vec::new(),
        }
    }

    fn write_file(root: &std::path::Path, rel: &str, body: &str) {
        let path = root.join(rel);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, body).unwrap();
    }

    #[test]
    fn manifest_rejects_escaping_templates_and_outputs() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().to_path_buf();
        let cfg = config_with_root(root.clone());
        for manifest in [
            "[files]\n\"../outside.md\" = \"entry.tpl\"\n",
            "[files]\n\"AGENTS.md\" = \"../outside.tpl\"\n",
        ] {
            write_file(
                &root,
                ".mochiflow/engine/adapters/agents/manifest.toml",
                manifest,
            );
            write_file(&root, ".mochiflow/engine/adapters/agents/entry.tpl", "safe");
            assert!(load_manifest(&cfg, "agents").is_err(), "{manifest}");
        }
    }

    #[cfg(unix)]
    #[test]
    fn manifest_rejects_template_symlink_escape() {
        use std::os::unix::fs::symlink;

        let tmp = tempfile::tempdir().unwrap();
        let outside = tempfile::tempdir().unwrap();
        let root = tmp.path().to_path_buf();
        let cfg = config_with_root(root.clone());
        write_file(
            &root,
            ".mochiflow/engine/adapters/agents/manifest.toml",
            "[files]\n\"AGENTS.md\" = \"link.tpl\"\n",
        );
        std::fs::write(outside.path().join("outside.tpl"), "unsafe").unwrap();
        symlink(
            outside.path().join("outside.tpl"),
            root.join(".mochiflow/engine/adapters/agents/link.tpl"),
        )
        .unwrap();
        assert!(load_manifest(&cfg, "agents").is_err());
    }

    const MARKERED: &str = "<!-- generated by mochiflow adapter=kiro version=1.1.0 -->\nbody\n";

    #[test]
    fn self_heal_removes_markered_outputs_and_reports_them() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().to_path_buf();
        // markered deprecated outputs, including the legacy hook
        write_file(&root, ".kiro/agents/spec-builder.json", MARKERED);
        write_file(&root, ".kiro/agents/spec-worker.json", MARKERED);
        write_file(&root, ".kiro/steering/spec-plan.md", MARKERED);
        write_file(
            &root,
            ".kiro/hooks/generate-project-index.kiro.hook",
            MARKERED,
        );
        let cfg = config_with_root(root.clone());
        let mut result = empty_result();

        self_heal_deprecated_kiro(&cfg, false, &mut result);

        for rel in [
            ".kiro/agents/spec-builder.json",
            ".kiro/agents/spec-worker.json",
            ".kiro/steering/spec-plan.md",
            ".kiro/hooks/generate-project-index.kiro.hook",
        ] {
            assert!(
                result.removed.iter().any(|r| r == rel),
                "expected {rel} reported removed: {:?}",
                result.removed
            );
            assert!(!root.join(rel).exists(), "{rel} should be deleted");
        }
        assert!(result.preserved.is_empty(), "{:?}", result.preserved);
    }

    #[test]
    fn self_heal_preserves_markerless_listed_and_ignores_unlisted() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().to_path_buf();
        // listed-but-markerless (user-edited): must be preserved, not deleted
        write_file(&root, ".kiro/steering/spec.md", "hand edited, no marker\n");
        write_file(
            &root,
            ".kiro/agents/spec-worker.json",
            "{\"name\":\"custom-worker\"}\n",
        );
        // unlisted user file: never scanned, removed, or reported
        write_file(&root, ".kiro/steering/release.md", "release notes\n");
        let cfg = config_with_root(root.clone());
        let mut result = empty_result();

        self_heal_deprecated_kiro(&cfg, false, &mut result);

        assert!(
            result
                .preserved
                .iter()
                .any(|r| r == ".kiro/steering/spec.md"),
            "expected spec.md preserved: {:?}",
            result.preserved
        );
        assert!(
            result
                .preserved
                .iter()
                .any(|r| r == ".kiro/agents/spec-worker.json"),
            "expected markerless worker residue preserved: {:?}",
            result.preserved
        );
        assert!(
            root.join(".kiro/steering/spec.md").exists(),
            "markerless listed file must be kept"
        );
        assert!(root.join(".kiro/agents/spec-worker.json").exists());
        assert!(root.join(".kiro/steering/release.md").exists());
        assert!(
            result.removed.is_empty(),
            "nothing should be removed: {:?}",
            result.removed
        );
        assert!(
            !result.preserved.iter().any(|r| r.contains("release.md")),
            "unlisted file must not be reported: {:?}",
            result.preserved
        );
    }

    #[test]
    fn self_heal_check_mode_flags_markered_residue_as_drift() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().to_path_buf();
        write_file(&root, ".kiro/agents/spec-builder.json", MARKERED);
        write_file(&root, ".kiro/agents/spec-worker.json", MARKERED);
        write_file(&root, ".kiro/steering/spec.md", "no marker\n");
        let cfg = config_with_root(root.clone());
        let mut result = empty_result();

        self_heal_deprecated_kiro(&cfg, true, &mut result);

        assert!(
            result
                .drift
                .iter()
                .any(|r| r == ".kiro/agents/spec-builder.json"),
            "markered residue must drift in check mode: {:?}",
            result.drift
        );
        assert!(
            result
                .drift
                .iter()
                .any(|r| r == ".kiro/agents/spec-worker.json"),
            "markered worker residue must drift in check mode: {:?}",
            result.drift
        );
        // markerless listed file is not drift, and the file is left in place
        assert!(!result.drift.iter().any(|r| r == ".kiro/steering/spec.md"));
        assert!(root.join(".kiro/agents/spec-builder.json").exists());
    }

    #[test]
    fn kiro_agent_json_matches_reviewer_only() {
        // Only the read-only reviewer profiles are generated Kiro agent JSON targets.
        assert!(is_kiro_agent_json(".kiro/agents/spec-plan-auditor.json"));
        assert!(is_kiro_agent_json(".kiro/agents/spec-change-reviewer.json"));
        assert!(!is_kiro_agent_json(
            ".kiro/agents/spec-independent-reviewer.json"
        ));
        assert!(!is_kiro_agent_json(".kiro/agents/spec-worker.json"));
        assert!(!is_kiro_agent_json(".kiro/agents/spec-builder.json"));
        assert!(!is_kiro_agent_json(".kiro/steering/mochiflow.md"));
    }

    #[test]
    fn removed_kiro_worker_is_deprecated_not_model_preserved() {
        // The retired worker is no longer a generated agent target. A markered
        // residue is handled by deprecated-output self-heal, not model
        // preservation.
        let worker = ".kiro/agents/spec-worker.json";
        let reviewer = ".kiro/agents/spec-change-reviewer.json";

        assert!(!is_kiro_agent_json(worker));
        assert!(!kiro_agent_preserves_model(worker));
        assert!(kiro_agent_preserves_model(reviewer));

        // reviewer still preserves a user-pinned model (regression guard).
        let r_rendered = "{\n  \"name\": \"spec-change-reviewer\",\n  \"model\": \"claude-opus-4.8\",\n  \"_generated\": \"generated by mochiflow adapter=kiro version=1.0.0\"\n}\n";
        let r_current = "{\n  \"name\": \"spec-change-reviewer\",\n  \"model\": \"user-pinned-model\",\n  \"_generated\": \"generated by mochiflow adapter=kiro version=1.0.0\"\n}\n";
        assert!(kiro_agent_matches_rendered(reviewer, r_current, r_rendered));
        let r_merged = preserve_kiro_agent_model(reviewer, Some(r_current), r_rendered);
        assert!(r_merged.contains("user-pinned-model"));
    }
}
