//! Adapter rendering: generate tool entrypoints from engine templates.
//!
//! Templates use {{placeholder}} tokens resolved from config.
//! Literal single braces (e.g. `{slug}`) are NOT expanded (AC-07).

use std::collections::BTreeMap;
use std::path::Path;

use crate::config::Config;
use crate::manifest::engine_version_label;

const MARKER_PREFIX: &str = "generated by mochiflow";
const MANAGED_BLOCK_END: &str = "<!-- mochiflow:end -->";

/// Resolve a user-facing adapter label to its canonical adapter ID.
///
/// `codex` is a recognizable tool name shown in the init menu / accepted on
/// `--adapter`, but its on-disk artifact (`AGENTS.md`) is produced by the
/// neutral `agents` adapter. All other labels map to themselves. Resolution is
/// applied only at the input boundary (CLI / prompt); `generate` and `doctor`
/// read the stored config verbatim so an unknown ID surfaces as schema-invalid
/// and a doctor FAIL.
pub fn resolve_adapter_label(label: &str) -> &str {
    match label {
        "codex" => "agents",
        other => other,
    }
}

/// Resolve a list of input labels to canonical IDs, preserving order and
/// removing duplicates (e.g. `["codex", "agents"]` -> `["agents"]`).
pub fn resolve_adapter_labels(labels: &[String]) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for label in labels {
        let id = resolve_adapter_label(label).to_string();
        if !out.contains(&id) {
            out.push(id);
        }
    }
    out
}

/// Build the substitution map from config (matching Python's _subs).
fn subs(cfg: &Config, tool: &str) -> BTreeMap<String, String> {
    let engine = format!("{}/engine", cfg.install_dir);
    let mut allow: Vec<String> = vec![
        format!("{}/**", cfg.specs_dir),
        cfg.constitution.project.clone(),
        cfg.constitution.local.clone(),
        cfg.context.product.clone(),
        cfg.context.structure.clone(),
        cfg.context.tech.clone(),
        cfg.adr.decisions.clone(),
        cfg.adr.pitfalls.clone(),
        cfg.index.clone(),
    ];
    allow.extend(cfg.write.allow.iter().cloned());

    let engine_version = engine_version_label(&cfg.engine_dir());
    let mut m = BTreeMap::new();
    m.insert(
        "marker".into(),
        format!("{MARKER_PREFIX} adapter={tool} version={engine_version}"),
    );
    m.insert("engine".into(), engine);
    m.insert("install_dir".into(), cfg.install_dir.clone());
    m.insert("specs_dir".into(), cfg.specs_dir.clone());
    m.insert("specs_glob".into(), format!("{}/**", cfg.specs_dir));
    m.insert("language".into(), cfg.language.clone());
    m.insert("engine_version".into(), engine_version);
    m.insert("adapter_tool".into(), tool.to_string());
    m.insert(
        "constitution.project".into(),
        cfg.constitution.project.clone(),
    );
    m.insert("constitution.local".into(), cfg.constitution.local.clone());
    m.insert("context.product".into(), cfg.context.product.clone());
    m.insert("context.structure".into(), cfg.context.structure.clone());
    m.insert("context.tech".into(), cfg.context.tech.clone());
    m.insert("adr.decisions".into(), cfg.adr.decisions.clone());
    m.insert("adr.pitfalls".into(), cfg.adr.pitfalls.clone());
    m.insert("index".into(), cfg.index.clone());
    m.insert("base_branch".into(), cfg.git.base_branch.clone());
    m.insert("pr_command".into(), cfg.git.pr_command.clone());
    m.insert(
        "allow_json".into(),
        serde_json::to_string_pretty(&allow).unwrap_or_default(),
    );
    m.insert(
        "deny_json".into(),
        serde_json::to_string_pretty(&cfg.write.deny).unwrap_or_default(),
    );
    m
}

/// Literal {{key}} replacement — does NOT touch single braces (AC-07).
pub fn render(template: &str, substitutions: &BTreeMap<String, String>) -> String {
    let mut result = template.to_string();
    for (key, value) in substitutions {
        let token = format!("{{{{{key}}}}}"); // produces "{{key}}"
        result = result.replace(&token, value);
    }
    result
}

fn is_kiro_agent_json(out_rel: &str) -> bool {
    matches!(
        out_rel,
        ".kiro/agents/spec-builder.json" | ".kiro/agents/spec-independent-reviewer.json"
    )
}

fn parse_json_object(content: &str) -> Option<serde_json::Map<String, serde_json::Value>> {
    match serde_json::from_str::<serde_json::Value>(content).ok()? {
        serde_json::Value::Object(obj) => Some(obj),
        _ => None,
    }
}

fn kiro_agent_matches_rendered(out_rel: &str, current: &str, rendered: &str) -> bool {
    if current == rendered {
        return true;
    }
    if !is_kiro_agent_json(out_rel) || !current.contains(MARKER_PREFIX) {
        return false;
    }

    let mut current_obj = match parse_json_object(current) {
        Some(obj) => obj,
        None => return false,
    };
    let mut rendered_obj = match parse_json_object(rendered) {
        Some(obj) => obj,
        None => return false,
    };
    current_obj.remove("model");
    rendered_obj.remove("model");
    current_obj == rendered_obj
}

fn is_embeddable_target(out_rel: &str) -> bool {
    out_rel.ends_with(".md")
}

fn managed_block_begin(tool: &str) -> String {
    format!("<!-- mochiflow:begin adapter={tool} -->")
}

fn managed_block(tool: &str, rendered: &str) -> String {
    let mut block = String::new();
    block.push_str(&managed_block_begin(tool));
    block.push('\n');
    block.push_str(rendered);
    if !block.ends_with('\n') {
        block.push('\n');
    }
    block.push_str(MANAGED_BLOCK_END);
    block.push('\n');
    block
}

fn managed_block_bounds(content: &str, tool: &str) -> Option<(usize, usize)> {
    let begin = managed_block_begin(tool);
    let start = content.find(&begin)?;
    let after_start = start + begin.len();
    let end_rel = content[after_start..].find(MANAGED_BLOCK_END)?;
    let mut end = after_start + end_rel + MANAGED_BLOCK_END.len();
    if content[end..].starts_with("\r\n") {
        end += 2;
    } else if content[end..].starts_with('\n') {
        end += 1;
    }
    Some((start, end))
}

fn replace_managed_block(content: &str, tool: &str, block: &str) -> Option<String> {
    let (start, end) = managed_block_bounds(content, tool)?;
    let mut out = String::new();
    out.push_str(&content[..start]);
    out.push_str(block);
    out.push_str(&content[end..]);
    Some(out)
}

fn append_managed_block(content: &str, block: &str) -> String {
    if content.is_empty() {
        return block.to_string();
    }

    let mut out = content.to_string();
    if !out.ends_with('\n') {
        out.push('\n');
    }
    if !out.ends_with("\n\n") {
        out.push('\n');
    }
    out.push_str(block);
    out
}

fn embeddable_target_matches_rendered(
    out_rel: &str,
    tool: &str,
    current: &str,
    rendered: &str,
) -> bool {
    if current == rendered {
        return true;
    }
    if !is_embeddable_target(out_rel) {
        return false;
    }
    let Some((start, end)) = managed_block_bounds(current, tool) else {
        return false;
    };
    current[start..end] == managed_block(tool, rendered)
}

fn preserve_kiro_agent_model(out_rel: &str, current: Option<&str>, rendered: &str) -> String {
    if !is_kiro_agent_json(out_rel) {
        return rendered.to_string();
    }

    let Some(current) = current else {
        return rendered.to_string();
    };
    if !current.contains(MARKER_PREFIX) {
        return rendered.to_string();
    }

    let Some(current_obj) = parse_json_object(current) else {
        return rendered.to_string();
    };
    let Some(model) = current_obj.get("model").cloned() else {
        return rendered.to_string();
    };
    let Some(mut rendered_obj) = parse_json_object(rendered) else {
        return rendered.to_string();
    };
    rendered_obj.insert("model".into(), model);
    match serde_json::to_string_pretty(&serde_json::Value::Object(rendered_obj)) {
        Ok(json) => format!("{json}\n"),
        Err(_) => rendered.to_string(),
    }
}

/// Load adapter manifest.toml → (adapter_dir, ordered file mappings).
///
/// File order matches the manifest's TOML declaration order (Python parity for
/// the `wrote:` / `DRIFT:` output); `toml`'s `preserve_order` feature keeps the
/// parsed table in insertion order.
fn load_manifest(cfg: &Config, tool: &str) -> Option<(std::path::PathBuf, Vec<(String, String)>)> {
    let adir = cfg.engine_dir().join("adapters").join(tool);
    let manifest_path = adir.join("manifest.toml");
    if !manifest_path.exists() {
        return None;
    }
    let text = std::fs::read_to_string(&manifest_path).ok()?;
    let data: toml::Value = text.parse().ok()?;
    let files = data.get("files")?.as_table()?;
    let map: Vec<(String, String)> = files
        .iter()
        .map(|(k, v)| (k.clone(), v.as_str().unwrap_or("").to_string()))
        .collect();
    Some((adir, map))
}

pub struct AdapterResult {
    pub drift: Vec<String>,
    pub wrote: Vec<String>,
    pub blocked: Vec<BlockedAdapter>,
    pub errors: Vec<String>,
}

pub struct BlockedAdapter {
    pub target: String,
    pub candidate: String,
}

/// Generate adapter files (or check for drift).
pub fn generate(cfg: &Config, check: bool, force: bool) -> AdapterResult {
    let mut result = AdapterResult {
        drift: Vec::new(),
        wrote: Vec::new(),
        blocked: Vec::new(),
        errors: Vec::new(),
    };

    for tool in &cfg.adapter_tools() {
        let (adir, files) = match load_manifest(cfg, tool) {
            Some(v) => v,
            None => continue,
        };
        let substitutions = subs(cfg, tool);

        for (out_rel, tpl_rel) in &files {
            let tpl_path = adir.join(tpl_rel);
            let template = match std::fs::read_to_string(&tpl_path) {
                Ok(t) => t,
                Err(_) => continue,
            };
            let rendered = render(&template, &substitutions);
            let target = cfg.repo_root.join(out_rel);
            let current = std::fs::read_to_string(&target).ok();

            if check {
                let matches = current.as_deref().is_some_and(|cur| {
                    embeddable_target_matches_rendered(out_rel, tool, cur, &rendered)
                        || kiro_agent_matches_rendered(out_rel, cur, &rendered)
                });
                if !matches {
                    result.drift.push(out_rel.clone());
                }
                continue;
            }

            if let Some(ref cur) = current
                && !force
            {
                if is_embeddable_target(out_rel) {
                    let block = managed_block(tool, &rendered);
                    let rendered = if managed_block_bounds(cur, tool).is_some() {
                        replace_managed_block(cur, tool, &block).unwrap_or_else(|| cur.clone())
                    } else if cur.contains(MARKER_PREFIX) {
                        rendered.clone()
                    } else {
                        append_managed_block(cur, &block)
                    };
                    if let Some(parent) = target.parent()
                        && let Err(e) = std::fs::create_dir_all(parent)
                    {
                        let parent_label = Path::new(out_rel)
                            .parent()
                            .map(|p| p.display().to_string())
                            .unwrap_or_else(|| ".".to_string());
                        result.errors.push(format!(
                            "could not create target parent for {out_rel} at {parent_label}: {e}"
                        ));
                        continue;
                    }
                    if let Err(e) = std::fs::write(&target, &rendered) {
                        result.errors.push(format!(
                            "could not write target for {out_rel} at {out_rel}: {e}"
                        ));
                        continue;
                    }
                    result.wrote.push(out_rel.clone());
                    continue;
                }

                if cur.contains(MARKER_PREFIX) {
                    // Managed non-embeddable targets fall through to full-file update.
                } else {
                    let candidate = format!("{}/state/adapters/{out_rel}", cfg.install_dir);
                    let candidate_path = cfg.repo_root.join(&candidate);
                    if let Some(parent) = candidate_path.parent()
                        && let Err(e) = std::fs::create_dir_all(parent)
                    {
                        let parent_label = Path::new(&candidate)
                            .parent()
                            .map(|p| p.display().to_string())
                            .unwrap_or_else(|| candidate.clone());
                        result.errors.push(format!(
                            "could not create candidate parent for {out_rel} at {parent_label}: {e}"
                        ));
                        continue;
                    }
                    if let Err(e) = std::fs::write(&candidate_path, &rendered) {
                        result.errors.push(format!(
                            "could not write candidate for {out_rel} at {candidate}: {e}"
                        ));
                        continue;
                    }
                    result.blocked.push(BlockedAdapter {
                        target: out_rel.clone(),
                        candidate,
                    });
                    continue;
                }
            }

            let rendered = preserve_kiro_agent_model(out_rel, current.as_deref(), &rendered);
            if let Some(parent) = target.parent()
                && let Err(e) = std::fs::create_dir_all(parent)
            {
                let parent_label = Path::new(out_rel)
                    .parent()
                    .map(|p| p.display().to_string())
                    .unwrap_or_else(|| ".".to_string());
                result.errors.push(format!(
                    "could not create target parent for {out_rel} at {parent_label}: {e}"
                ));
                continue;
            }
            if let Err(e) = std::fs::write(&target, &rendered) {
                result.errors.push(format!(
                    "could not write target for {out_rel} at {out_rel}: {e}"
                ));
                continue;
            }
            result.wrote.push(out_rel.clone());
        }
    }

    result
}

/// CLI entry point for `adapter generate`.
pub fn cmd_adapter_generate(cfg: &Config, check: bool, force: bool) -> i32 {
    let result = generate(cfg, check, force);
    if check {
        for f in &result.drift {
            println!("DRIFT: {f}");
        }
        println!("\nSummary: {} drift", result.drift.len());
        if result.drift.is_empty() { 0 } else { 1 }
    } else {
        for f in &result.wrote {
            println!("wrote: {f}");
        }
        for blocked in &result.blocked {
            println!(
                "BLOCKED: {} (candidate: {}; merge manually or use --force to replace)",
                blocked.target, blocked.candidate
            );
        }
        for error in &result.errors {
            println!("FAIL: {error}");
        }
        println!(
            "\nSummary: {} written, {} blocked, {} failed",
            result.wrote.len(),
            result.blocked.len(),
            result.errors.len()
        );
        if result.blocked.is_empty() && result.errors.is_empty() {
            0
        } else {
            1
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn subs_exposes_layer_tokens_and_allows_all_living_spec_paths() {
        use crate::config::{
            Config, RawAdapter, RawAdr, RawConstitution, RawContext, RawGit, RawWrite,
        };
        let cfg = Config {
            schema_version: 1,
            language: "en".into(),
            install_dir: ".mochiflow".into(),
            specs_dir: ".mochiflow/specs".into(),
            index: ".mochiflow/INDEX.md".into(),
            constitution: RawConstitution {
                project: ".mochiflow/constitution.md".into(),
                local: ".mochiflow/constitution.local.md".into(),
            },
            context: RawContext {
                product: ".mochiflow/context/product.md".into(),
                structure: ".mochiflow/context/structure.md".into(),
                tech: ".mochiflow/context/tech.md".into(),
            },
            adr: RawAdr {
                decisions: ".mochiflow/adr/decisions.md".into(),
                pitfalls: ".mochiflow/adr/pitfalls.md".into(),
            },
            git: RawGit::default(),
            adapter: RawAdapter::default(),
            write: RawWrite::default(),
            surfaces: BTreeMap::new(),
            repo_root: std::path::PathBuf::from("/tmp"),
            config_path: std::path::PathBuf::from("/tmp/.mochiflow/config.toml"),
        };
        let m = subs(&cfg, "kiro");
        assert_eq!(
            m.get("context.product").map(String::as_str),
            Some(".mochiflow/context/product.md")
        );
        assert_eq!(
            m.get("context.structure").map(String::as_str),
            Some(".mochiflow/context/structure.md")
        );
        assert_eq!(
            m.get("context.tech").map(String::as_str),
            Some(".mochiflow/context/tech.md")
        );
        assert_eq!(
            m.get("adr.decisions").map(String::as_str),
            Some(".mochiflow/adr/decisions.md")
        );
        assert_eq!(
            m.get("adr.pitfalls").map(String::as_str),
            Some(".mochiflow/adr/pitfalls.md")
        );
        assert_eq!(
            m.get("constitution.project").map(String::as_str),
            Some(".mochiflow/constitution.md")
        );
        assert_eq!(
            m.get("constitution.local").map(String::as_str),
            Some(".mochiflow/constitution.local.md")
        );
        // legacy flat tokens are gone
        assert!(!m.contains_key("paths.architecture"));
        assert!(!m.contains_key("paths.structure"));
        // write allow lists all four living-spec paths + index
        assert!(m.contains_key("allow_json"), "allow_json missing");
        let allow = m.get("allow_json").map(String::as_str).unwrap_or("");
        for p in [
            ".mochiflow/constitution.md",
            ".mochiflow/constitution.local.md",
            ".mochiflow/context/product.md",
            ".mochiflow/context/structure.md",
            ".mochiflow/context/tech.md",
            ".mochiflow/adr/decisions.md",
            ".mochiflow/adr/pitfalls.md",
            ".mochiflow/INDEX.md",
        ] {
            assert!(allow.contains(p), "allow_json missing {p}: {allow}");
        }
    }

    #[test]
    fn resolve_label_codex_to_agents() {
        assert_eq!(resolve_adapter_label("codex"), "agents");
    }

    #[test]
    fn resolve_label_identity_for_others() {
        assert_eq!(resolve_adapter_label("agents"), "agents");
        assert_eq!(resolve_adapter_label("kiro"), "kiro");
        assert_eq!(resolve_adapter_label("claude-code"), "claude-code");
        assert_eq!(resolve_adapter_label("copilot"), "copilot");
        // unknown labels pass through unchanged (doctor/schema reject them)
        assert_eq!(resolve_adapter_label("foo"), "foo");
    }

    #[test]
    fn resolve_labels_dedupes_preserving_order() {
        let input = vec![
            "codex".to_string(),
            "agents".to_string(),
            "kiro".to_string(),
        ];
        assert_eq!(resolve_adapter_labels(&input), vec!["agents", "kiro"]);
    }

    #[test]
    fn render_replaces_double_brace_tokens() {
        let mut subs = BTreeMap::new();
        subs.insert("engine".to_string(), ".mochiflow/engine".to_string());
        subs.insert("language".to_string(), "ja".to_string());
        let out = render("engine={{engine}} lang={{language}}", &subs);
        assert_eq!(out, "engine=.mochiflow/engine lang=ja");
    }

    #[test]
    fn render_leaves_single_brace_literal_untouched() {
        // AC-07: literal single-brace tokens like {slug} must NOT be expanded.
        let mut subs = BTreeMap::new();
        subs.insert("slug".to_string(), "SHOULD-NOT-APPEAR".to_string());
        let out = render("path/{slug}/spec.yaml and {{slug}}", &subs);
        assert_eq!(out, "path/{slug}/spec.yaml and SHOULD-NOT-APPEAR");
    }

    #[test]
    fn render_repeats_and_missing_keys() {
        let mut subs = BTreeMap::new();
        subs.insert("k".to_string(), "V".to_string());
        // repeated token replaced everywhere; unknown {{x}} left as-is
        assert_eq!(render("{{k}}-{{k}}-{{x}}", &subs), "V-V-{{x}}");
    }
}
