name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@v6
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      # dtolnay/rust-toolchain@master
      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: 1.96.0
          components: rustfmt, clippy
      - run: cargo test --manifest-path cli/Cargo.toml
      - run: cargo fmt --manifest-path cli/Cargo.toml --all -- --check
      - run: cargo clippy --manifest-path cli/Cargo.toml --all-targets -- -D warnings

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@v6
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      # EmbarkStudios/cargo-deny-action@v2
      - uses: EmbarkStudios/cargo-deny-action@8f84122a46a358a27cb0625d85ad60ab436a1b87
        with:
          manifest-path: cli/Cargo.toml
          command: check
          command-arguments: --config cli/deny.toml
